# Generated by Django 4.2.2 on 2023-08-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='modulo_fiscal',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='prs',
        ),
    ]
