# Generated by Django 4.2.2 on 2023-09-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_statusservico_ordemservico_itemservico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordem_servico_item', to='core.item', verbose_name='Item para ser reciclado'),
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='qtd',
            field=models.PositiveIntegerField(verbose_name='Quantidade do mesmo item'),
        ),
    ]
