# Generated by Django 4.2.2 on 2023-10-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_statusitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemservico',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens_status', to='core.statusitem'),
        ),
    ]
