# Generated by Django 4.2.2 on 2023-10-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itemservico_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemservico',
            options={'ordering': ['id']},
        ),
    ]
