# Generated by Django 4.2.2 on 2023-09-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
