# Generated by Django 4.2.2 on 2023-09-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0002_alter_morador_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='latitude',
            field=models.DecimalField(decimal_places=18, help_text='Coordenada geográfica da sua residência', max_digits=20, max_length=255, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='longitude',
            field=models.DecimalField(decimal_places=18, help_text='Coordenada geográfica da sua residência', max_digits=20, max_length=255, verbose_name='longitude'),
        ),
    ]
